/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.demo;

import java.util.HashMap;

import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import org.objectweb.asm.commons.GeneratorAdapter;
import org.objectweb.asm.commons.Method;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static byte[] generateGreeter() {
        ClassWriter cw = new ClassWriter(0);
        cw.visit(Opcodes.V1_8, Opcodes.ACC_PUBLIC, "Greeter", null, "java/lang/Object", null);
        cw.visitSource("Greeter.java", null);

        MethodVisitor mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "<init>", "()V", null, null);
        mv.visitCode();
        mv.visitVarInsn(Opcodes.ALOAD, 0);
        mv.visitMethodInsn(Opcodes.INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        mv.visitInsn(Opcodes.RETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        mv = cw.visitMethod(Opcodes.ACC_PUBLIC, "toString", "()Ljava/lang/String;", null, null);
        mv.visitCode();
        mv.visitLdcInsn("Hello from Greeter!");
        mv.visitInsn(Opcodes.ARETURN);
        mv.visitMaxs(1, 1);
        mv.visitEnd();

        cw.visitEnd();

        byte[] bytecode = cw.toByteArray();
        return bytecode;
    }

    public static void main(String[] args) {
        ByteArrayClassLoader classLoader = new ByteArrayClassLoader(App.class.getClassLoader());

        classLoader.addClassData("Greeter", generateGreeter());

        try {
            Class<?> greeterClass = Class.forName("Greeter", true, classLoader);
            Object greeter = greeterClass.getDeclaredConstructor().newInstance();
            System.out.println(greeter);
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
