/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void greeterHasAGreeting() {
        Greeter classUnderTest = new Greeter();
        assertNotNull("Greeter should have a greeting", classUnderTest.getGreeting());
    }
}
